# Generated by Django 4.2.4 on 2023-08-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparepartsApp', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_name',
            new_name='part_name',
        ),
    ]
