# Generated by Django 4.2.4 on 2023-08-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparepartsApp', '0006_remove_product_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.IntegerField(default=0),
        ),
    ]
