# Generated by Django 4.2.4 on 2023-08-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparepartsApp', '0008_alter_product_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='part_number',
        ),
    ]
