# Generated by Django 4.2.4 on 2023-08-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparepartsApp', '0014_rename_item_orgin_product_country_of_orgin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
