# Generated by Django 4.2.4 on 2023-08-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparepartsApp', '0016_rename_issued_to_sale_customers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='phone_number',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
