# Generated by Django 4.2.4 on 2023-08-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparepartsApp', '0017_sale_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
