# Generated by Django 4.2.4 on 2023-08-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparepartsApp', '0018_remove_product_id_alter_product_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='part_number',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
